workflows:
  build-ios-app:
    name: Build iOS Simulator App
    max_build_duration: 15
    instance_type: mac_mini_m1
    environment:
      vars:
        XAMARIN_IOS_PROJECT: "Skyshobe/Skyshobe.csproj"
        XAMARIN_SOLUTION: "Skyshobe.sln"
      xcode: latest
    scripts:
      - name: Install .NET SDK
        script: |
          brew install --cask dotnet-sdk
          export PATH="/usr/local/share/dotnet:$PATH"
      - name: Install Mono
        script: |
          brew install mono-mdk
      - name: Restore NuGet packages
        script: |
          dotnet restore $XAMARIN_SOLUTION
      - name: Build iOS app
        script: |
          msbuild $XAMARIN_IOS_PROJECT /p:Configuration=Debug /p:Platform=iPhoneSimulator
    artifacts:
      - build/**/iPhoneSimulator/Debug/*.app
